service: aws-bedrock-serverless

frameworkVersion: "3"

provider:
  name: aws
  architecture: arm64
  runtime: python3.11
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: "s3:ListBucket"
          Resource: "*"
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - "s3:GetObject"
          Resource:
            - "arn:aws:s3:::${ssm:/dev/s3/BedrockDemo/files}/*"
        # Allow functions to list all buckets
        - Effect: Allow
          Action: "bedrock:ListFoundationModels"
          Resource: "*"
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - "bedrock:InvokeModel"
          Resource:
            - "arn:aws:bedrock:us-east-1::foundation-model/ai21.j2-ultra-v1"

functions:
  bedrockDemo:
    handler: handler.bedrockDemo
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-arm64-boto3:4
    events:
      - s3:
          bucket: ${ssm:/dev/s3/BedrockDemo/files}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .txt
